"use client";
import{DragEvent,useEffect,useRef,useState}from"react";import{AlertTriangle,Camera,CheckCircle2,Images,ScanLine,Trash2,Upload}from"lucide-react";import{Button}from"@/components/ui/button";
export type ProductScan={product_name:string|null;composition:string|null;pack_size:string|null;batch_number:string|null;mfg_date:string|null;expiry_date:string|null;mrp:string|null;marketed_by:string|null;manufactured_by:string|null;warnings:string[];confidence:Record<string,number>;evidence:Record<string,number[]>};
type Shot={file:File;url:string};
export function ProductImageScanner({onResult}:{onResult:(x:ProductScan)=>void}){const gallery=useRef<HTMLInputElement>(null),camera=useRef<HTMLInputElement>(null),shotsRef=useRef<Shot[]>([]),inFlight=useRef(false),abortRef=useRef<AbortController|null>(null),mounted=useRef(true),[shots,setShots]=useState<Shot[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[ok,setOk]=useState(false),[drag,setDrag]=useState(false);shotsRef.current=shots;useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;abortRef.current?.abort();shotsRef.current.forEach(x=>URL.revokeObjectURL(x.url));shotsRef.current=[]}},[]);function clearTemporaryImages(){setShots(old=>{old.forEach(x=>URL.revokeObjectURL(x.url));return[]});shotsRef.current=[];if(gallery.current)gallery.current.value="";if(camera.current)camera.current.value=""}function add(list:FileList|File[]){if(inFlight.current)return;const files=Array.from(list).filter(x=>["image/jpeg","image/png","image/webp"].includes(x.type)&&x.size<=8*1024*1024).slice(0,3-shots.length);if(!files.length){setMessage("Use clear JPG, PNG or WebP photos up to 8 MB each.");return}if(shots.reduce((sum,x)=>sum+x.file.size,0)+files.reduce((sum,x)=>sum+x.size,0)>20*1024*1024){setMessage("Use photos totaling no more than 20 MB.");return}setShots(old=>[...old,...files.map(file=>({file,url:URL.createObjectURL(file)}))]);setMessage("");setOk(false)}function remove(i:number){setShots(old=>{URL.revokeObjectURL(old[i].url);return old.filter((_,n)=>n!==i)})}function drop(e:DragEvent){e.preventDefault();setDrag(false);add(e.dataTransfer.files)}async function scan(){
 if(inFlight.current)return;
 if(shots.length<2){setMessage("Add at least 2 photos of the same product.");return}
 inFlight.current=true;const controller=new AbortController();abortRef.current=controller;
 const timer=setTimeout(()=>controller.abort(),90000);
 setBusy(true);setOk(false);setMessage("Analyzing every image together with pharmaceutical vision…");
 try{
  const form=new FormData();shots.forEach(x=>form.append("images",x.file));
  const r=await fetch("/api/product-scan",{method:"POST",body:form,cache:"no-store",signal:controller.signal});
  let body;
  try{body=await r.json()}catch{throw new Error(r.status===401?"Your session expired. Sign in again before scanning.":"The server returned an incomplete or non-JSON response. Please retry.")}
  if(!r.ok)throw new Error((r.status===401?"Your session expired. Sign in again before scanning.":body.error||"Unable to analyze packaging")+(body.requestId?" Reference: "+body.requestId:""));
  const keys=["product_name","composition","pack_size","batch_number","mfg_date","expiry_date","mrp","marketed_by","manufactured_by"];
  if(!body.data||!keys.every(key=>body.data[key]===null||typeof body.data[key]==="string")||!Array.isArray(body.validation?.warnings))throw new Error("The server returned incomplete extraction data. Please retry.");
  if(!mounted.current)return;
  const result:ProductScan={...body.data,...body.validation};
  onResult(result);setOk(true);setMessage(result.warnings?.[0]||"Extraction complete. Review highlighted fields before saving.");
 }catch(e){
  if(mounted.current)setMessage((controller.signal.aborted?"The scan timed out. Please retry.":e instanceof TypeError?"Could not connect to the scanner. Check your connection and retry.":e instanceof Error?e.message:"The scan failed. Please retry.")+" Existing product fields have been kept. Select the photos again to retry.");
 }finally{
  clearTimeout(timer);abortRef.current=null;inFlight.current=false;
  if(mounted.current){clearTemporaryImages();setBusy(false)}
 }
}return <section className="product-scanner multi-scanner"><input ref={gallery} hidden multiple type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>e.target.files&&add(e.target.files)}/><input ref={camera} hidden type="file" accept="image/*" capture="environment" onChange={e=>e.target.files&&add(e.target.files)}/><div className={`multi-dropzone ${drag?"drag":""}`} onDragOver={e=>{e.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={drop}><header><div><Images/><span><b>Upload 2–3 photos in any order</b><small>Every image is searched for all field anchors</small></span></div><em>{shots.length}/3</em></header><div className="scan-thumbnails">{shots.map((s,i)=><article key={s.url}><img src={s.url} alt={`Product photo ${i+1}`}/><span>Product photo {i+1}</span><button type="button" disabled={busy} aria-label={`Remove photo ${i+1}`} onClick={()=>remove(i)}><Trash2/></button><i>{i+1}</i></article>)}{shots.length<3&&<button type="button" className="add-scan-photo" disabled={busy} onClick={()=>gallery.current?.click()}><Upload/><b>Add photo</b><small>Any product side</small></button>}</div><div className="capture-actions"><Button type="button" variant="outline" disabled={busy||shots.length===3} onClick={()=>camera.current?.click()}><Camera/>Use camera</Button><Button type="button" variant="outline" disabled={busy||shots.length===3} onClick={()=>gallery.current?.click()}><Upload/>Choose files</Button></div></div><Button type="button" className="analyze-images" disabled={busy||shots.length<2} onClick={scan}>{busy?<ScanLine className="spin"/>:<ScanLine/>}{busy?"Analyzing packaging images…":`Analyze ${shots.length||""} images`}</Button>{message&&<div className={`scan-status ${ok?"ok":""}`}>{ok?<CheckCircle2/>:<AlertTriangle/>}<span>{message}</span></div>}</section>}
