CREATE TABLE `agency_profiles` (
	`tenant_id` text PRIMARY KEY NOT NULL,
	`trade_name` text NOT NULL,
	`legal_entity` text DEFAULT '' NOT NULL,
	`tagline` text DEFAULT 'Medical and pharmaceutical wholesale distribution' NOT NULL,
	`logo_key` text,
	`gstin` text DEFAULT '' NOT NULL,
	`state` text DEFAULT 'Telangana' NOT NULL,
	`state_code` text DEFAULT '36' NOT NULL,
	`dl_no_20b` text DEFAULT '' NOT NULL,
	`dl_no_21b` text DEFAULT '' NOT NULL,
	`fssai` text DEFAULT '' NOT NULL,
	`pan` text DEFAULT '' NOT NULL,
	`street_address` text DEFAULT '' NOT NULL,
	`city` text DEFAULT '' NOT NULL,
	`district` text DEFAULT '' NOT NULL,
	`pin_code` text DEFAULT '' NOT NULL,
	`booking_location` text DEFAULT '' NOT NULL,
	`phones` text DEFAULT '' NOT NULL,
	`email` text DEFAULT '' NOT NULL,
	`website` text DEFAULT '' NOT NULL,
	`bank_name` text DEFAULT '' NOT NULL,
	`account_holder` text DEFAULT '' NOT NULL,
	`account_number` text DEFAULT '' NOT NULL,
	`ifsc` text DEFAULT '' NOT NULL,
	`branch_name` text DEFAULT '' NOT NULL,
	`terms` text DEFAULT '1. Goods once sold will not be taken back.
2. Subject to local jurisdiction only.' NOT NULL,
	`signatory_title` text DEFAULT 'Authorised Signatory' NOT NULL,
	`signature_key` text,
	`updated_at` integer NOT NULL,
	FOREIGN KEY (`tenant_id`) REFERENCES `tenants`(`id`) ON UPDATE no action ON DELETE no action
);
