import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { apiClient, GstSummary, SupplierLedger } from '@/services/api'

const money=(v:string|number|undefined)=>`₹${Number(v||0).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})}`
const today=()=>new Date().toISOString().slice(0,10)

export default function Accounting(){
  const [ledgers,setLedgers]=useState<SupplierLedger[]>([])
  const [selected,setSelected]=useState<SupplierLedger|null>(null)
  const [gst,setGst]=useState<GstSummary|null>(null)
  const [search,setSearch]=useState('')
  const [outstandingOnly,setOutstandingOnly]=useState(true)
  const [fromDate,setFromDate]=useState('')
  const [toDate,setToDate]=useState(today())
  const [pay,setPay]=useState({amount:'',payment_date:today(),payment_mode:'BANK',reference_number:'',notes:''})
  const [error,setError]=useState(''); const [success,setSuccess]=useState(''); const [loading,setLoading]=useState(true)

  const load=async()=>{setLoading(true);setError('');try{const [s,g]=await Promise.all([apiClient.listSupplierLedgers({search:search||undefined,outstanding_only:outstandingOnly}),apiClient.getGstSummary({from_date:fromDate||undefined,to_date:toDate||undefined})]);setLedgers(s);setGst(g);if(selected){const fresh=await apiClient.getSupplierLedger(selected.supplier_id);setSelected(fresh)}}catch(e:any){setError(e?.response?.data?.detail||'Unable to load accounting data')}finally{setLoading(false)}}
  useEffect(()=>{load()},[])
  const totalPayables=useMemo(()=>ledgers.reduce((n,x)=>n+Number(x.outstanding||0),0),[ledgers])

  const receive=async(e:React.FormEvent)=>{e.preventDefault();if(!selected)return;setError('');setSuccess('');try{await apiClient.createSupplierPayment({supplier_id:selected.supplier_id,amount:Number(pay.amount),payment_date:pay.payment_date,payment_mode:pay.payment_mode,reference_number:pay.reference_number||null,notes:pay.notes||null});setSuccess('Supplier payment recorded successfully.');setPay({...pay,amount:'',reference_number:'',notes:''});await load()}catch(e:any){setError(e?.response?.data?.detail||'Unable to record supplier payment')}}

  return <div className="min-h-screen bg-gray-50 p-6"><div className="mx-auto max-w-7xl">
    <div className="mb-6 flex items-center justify-between"><div><h1 className="text-2xl font-bold">Accounting, Payables & GST</h1><p className="text-sm text-gray-500">Supplier ledgers, payments and GST summary net of returns.</p></div><Link to="/dashboard" className="rounded border bg-white px-4 py-2">Dashboard</Link></div>
    {error&&<div className="mb-4 rounded border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}{success&&<div className="mb-4 rounded border border-green-200 bg-green-50 p-3 text-sm text-green-700">{success}</div>}
    <div className="mb-6 grid gap-4 md:grid-cols-4"><Card title="Supplier Payables" value={money(totalPayables)}/><Card title="Net Output GST" value={money(gst?.net_output_gst)}/><Card title="Net Input GST" value={money(gst?.net_input_gst)}/><Card title="Est. GST Payable" value={money(gst?.estimated_net_gst_payable)}/></div>
    <div className="mb-6 rounded bg-white p-4 shadow-sm"><div className="grid gap-3 md:grid-cols-5"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Supplier / code / GSTIN" className="rounded border px-3 py-2"/><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={outstandingOnly} onChange={e=>setOutstandingOnly(e.target.checked)}/> Outstanding only</label><input type="date" value={fromDate} onChange={e=>setFromDate(e.target.value)} className="rounded border px-3 py-2"/><input type="date" value={toDate} onChange={e=>setToDate(e.target.value)} className="rounded border px-3 py-2"/><button onClick={load} className="rounded bg-blue-600 px-4 py-2 text-white">Apply</button></div></div>
    <div className="grid gap-6 lg:grid-cols-2"><div className="rounded bg-white shadow-sm"><div className="border-b p-4 font-semibold">Supplier outstanding</div>{loading?<div className="p-6 text-gray-500">Loading...</div>:<div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b bg-gray-50"><th className="p-3 text-left">Supplier</th><th className="p-3 text-right">Purchases</th><th className="p-3 text-right">Returns</th><th className="p-3 text-right">Paid</th><th className="p-3 text-right">Outstanding</th></tr></thead><tbody>{ledgers.map(x=><tr key={x.supplier_id} onClick={()=>apiClient.getSupplierLedger(x.supplier_id).then(setSelected)} className="cursor-pointer border-b hover:bg-blue-50"><td className="p-3">{x.supplier_name}<div className="text-xs text-gray-500">{x.supplier_code}</div></td><td className="p-3 text-right">{money(x.total_purchases)}</td><td className="p-3 text-right">{money(x.total_returns)}</td><td className="p-3 text-right">{money(x.total_payments)}</td><td className="p-3 text-right font-semibold">{money(x.outstanding)}</td></tr>)}</tbody></table></div>}</div>
      <div className="rounded bg-white p-5 shadow-sm"><h2 className="mb-3 font-semibold">{selected?selected.supplier_name:'Select a supplier'}</h2>{selected&&<><div className="mb-4 max-h-64 overflow-auto"><table className="w-full text-xs"><thead><tr><th className="p-2 text-left">Date</th><th className="p-2 text-left">Type</th><th className="p-2 text-left">Reference</th><th className="p-2 text-right">Debit</th><th className="p-2 text-right">Credit</th><th className="p-2 text-right">Balance</th></tr></thead><tbody>{selected.rows.map((r,i)=><tr key={i} className="border-t"><td className="p-2">{r.entry_date}</td><td className="p-2">{r.entry_type}</td><td className="p-2">{r.reference}</td><td className="p-2 text-right">{money(r.debit)}</td><td className="p-2 text-right">{money(r.credit)}</td><td className="p-2 text-right">{money(r.balance)}</td></tr>)}</tbody></table></div><form onSubmit={receive} className="grid gap-2 md:grid-cols-2"><input required type="number" min="0.01" step="0.01" max={selected.outstanding} value={pay.amount} onChange={e=>setPay({...pay,amount:e.target.value})} placeholder={`Pay up to ${selected.outstanding}`} className="rounded border px-3 py-2"/><input required type="date" value={pay.payment_date} max={today()} onChange={e=>setPay({...pay,payment_date:e.target.value})} className="rounded border px-3 py-2"/><select value={pay.payment_mode} onChange={e=>setPay({...pay,payment_mode:e.target.value})} className="rounded border px-3 py-2"><option>BANK</option><option>UPI</option><option>CASH</option><option>CHEQUE</option><option>CARD</option></select><input value={pay.reference_number} onChange={e=>setPay({...pay,reference_number:e.target.value})} placeholder="Reference" className="rounded border px-3 py-2"/><button className="rounded bg-gray-900 px-4 py-2 text-white md:col-span-2">Record Supplier Payment</button></form></>}</div></div>
    <div className="mt-6 rounded bg-white p-5 shadow-sm"><h2 className="mb-4 font-semibold">GST Summary</h2><div className="grid gap-4 md:grid-cols-3"><Stat label="Net taxable sales" value={gst?.taxable_sales}/><Stat label="Sales GST" value={gst?.sales_gst_total}/><Stat label="Sales return taxable" value={gst?.sales_returns_taxable}/><Stat label="Net taxable purchases" value={gst?.taxable_purchases}/><Stat label="Purchase GST" value={gst?.purchase_gst_total}/><Stat label="Purchase return taxable" value={gst?.purchase_returns_taxable}/></div><p className="mt-4 text-xs text-gray-500">This is an operational GST summary from posted transactions, not a statutory GST return filing engine.</p></div>
  </div></div>
}
function Card({title,value}:{title:string;value:string}){return <div className="rounded bg-white p-5 shadow-sm"><div className="text-sm text-gray-500">{title}</div><div className="mt-1 text-2xl font-bold">{value}</div></div>}
function Stat({label,value}:{label:string;value:string|undefined}){return <div><div className="text-xs text-gray-500">{label}</div><div className="font-semibold">{money(value)}</div></div>}
