import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { adminApi, AdminUserInfo, AuditLogInfo, BusinessControls, PermissionInfo, RoleInfo } from '@/services/adminApi'

type Tab='users'|'roles'|'audit'|'controls'

export default function Admin(){
  const [tab,setTab]=useState<Tab>('users')
  const [users,setUsers]=useState<AdminUserInfo[]>([])
  const [roles,setRoles]=useState<RoleInfo[]>([])
  const [permissions,setPermissions]=useState<PermissionInfo[]>([])
  const [audits,setAudits]=useState<AuditLogInfo[]>([])
  const [controls,setControls]=useState<BusinessControls|null>(null)
  const [error,setError]=useState(''); const [success,setSuccess]=useState(''); const [loading,setLoading]=useState(true)
  const [newUser,setNewUser]=useState({name:'',email:'',mobile:'',password:'',role_id:''})
  const [newRole,setNewRole]=useState({name:'',description:'',permission_ids:[] as number[]})

  const load=async()=>{setLoading(true);setError('');try{const [u,r,p,a,c]=await Promise.all([adminApi.users(),adminApi.roles(),adminApi.permissions(),adminApi.audits({limit:200}),adminApi.controls()]);setUsers(u);setRoles(r);setPermissions(p);setAudits(a);setControls(c)}catch(e:any){setError(e?.response?.data?.detail||'Unable to load administration data')}finally{setLoading(false)}}
  useEffect(()=>{load()},[])

  const createUser=async(e:React.FormEvent)=>{e.preventDefault();setError('');try{await adminApi.createUser({name:newUser.name,email:newUser.email,mobile:newUser.mobile||null,password:newUser.password,role_ids:[Number(newUser.role_id)]});setNewUser({name:'',email:'',mobile:'',password:'',role_id:''});setSuccess('User created');await load()}catch(e:any){setError(e?.response?.data?.detail||'Unable to create user')}}
  const toggleUser=async(u:AdminUserInfo)=>{setError('');try{await adminApi.updateUser(u.id,{is_active:!u.is_active});setSuccess(`User ${u.is_active?'deactivated':'activated'}`);await load()}catch(e:any){setError(e?.response?.data?.detail||'Unable to update user')}}
  const createRole=async(e:React.FormEvent)=>{e.preventDefault();setError('');try{await adminApi.createRole({name:newRole.name,description:newRole.description||null,permission_ids:newRole.permission_ids});setNewRole({name:'',description:'',permission_ids:[]});setSuccess('Role created');await load()}catch(e:any){setError(e?.response?.data?.detail||'Unable to create role')}}
  const saveControls=async(e:React.FormEvent)=>{e.preventDefault();if(!controls)return;setError('');try{setControls(await adminApi.updateControls({invoice_prefix:controls.invoice_prefix,default_payment_mode:controls.default_payment_mode,currency:controls.currency,selected_invoice_template:controls.selected_invoice_template}));setSuccess('Business controls saved');await load()}catch(e:any){setError(e?.response?.data?.detail||'Unable to save controls')}}

  return <div className="min-h-screen bg-gray-50 p-6"><div className="mx-auto max-w-7xl">
    <div className="mb-6 flex items-start justify-between"><div><h1 className="text-2xl font-bold">Administration & Controls</h1><p className="text-sm text-gray-500">Users, roles, permissions, audit trail and company business controls.</p></div><Link to="/dashboard" className="rounded border bg-white px-4 py-2">Dashboard</Link></div>
    {error&&<div className="mb-4 rounded border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}{success&&<div className="mb-4 rounded border border-green-200 bg-green-50 p-3 text-sm text-green-700">{success}</div>}
    <div className="mb-5 flex flex-wrap gap-2">{(['users','roles','audit','controls'] as Tab[]).map(t=><button key={t} onClick={()=>setTab(t)} className={`rounded px-4 py-2 ${tab===t?'bg-blue-600 text-white':'border bg-white'}`}>{t==='users'?'Users':t==='roles'?'Roles & Permissions':t==='audit'?'Audit Trail':'Business Controls'}</button>)}</div>
    {loading?<div className="rounded bg-white p-8 text-center text-gray-500">Loading...</div>:<>
      {tab==='users'&&<div className="grid gap-6 lg:grid-cols-[360px_1fr]"><form onSubmit={createUser} className="rounded-lg border bg-white p-5"><h2 className="mb-4 font-semibold">Create user</h2><div className="space-y-3"><input required className="w-full rounded border px-3 py-2" placeholder="Name" value={newUser.name} onChange={e=>setNewUser({...newUser,name:e.target.value})}/><input required type="email" className="w-full rounded border px-3 py-2" placeholder="Email" value={newUser.email} onChange={e=>setNewUser({...newUser,email:e.target.value})}/><input className="w-full rounded border px-3 py-2" placeholder="Mobile" value={newUser.mobile} onChange={e=>setNewUser({...newUser,mobile:e.target.value})}/><input required type="password" minLength={8} className="w-full rounded border px-3 py-2" placeholder="Temporary password" value={newUser.password} onChange={e=>setNewUser({...newUser,password:e.target.value})}/><select required className="w-full rounded border px-3 py-2" value={newUser.role_id} onChange={e=>setNewUser({...newUser,role_id:e.target.value})}><option value="">Select role</option>{roles.filter(r=>r.is_active).map(r=><option value={r.id} key={r.id}>{r.name}</option>)}</select><button className="w-full rounded bg-blue-600 px-4 py-2 text-white">Create User</button></div></form><div className="overflow-x-auto rounded-lg border bg-white"><table className="min-w-full text-sm"><thead className="bg-gray-50"><tr><th className="p-3 text-left">User</th><th className="p-3 text-left">Roles</th><th className="p-3 text-left">Last login</th><th className="p-3 text-left">Status</th><th className="p-3"></th></tr></thead><tbody>{users.map(u=><tr key={u.id} className="border-t"><td className="p-3"><div className="font-medium">{u.name}</div><div className="text-gray-500">{u.email}{u.mobile?` · ${u.mobile}`:''}</div></td><td className="p-3">{u.roles.map(r=>r.name).join(', ')||'-'}</td><td className="p-3">{u.last_login_at?new Date(u.last_login_at).toLocaleString():'Never'}</td><td className="p-3">{u.is_active?'Active':'Inactive'}</td><td className="p-3 text-right"><button onClick={()=>toggleUser(u)} className="rounded border px-3 py-1">{u.is_active?'Deactivate':'Activate'}</button></td></tr>)}</tbody></table></div></div>}
      {tab==='roles'&&<div className="grid gap-6 lg:grid-cols-[420px_1fr]"><form onSubmit={createRole} className="rounded-lg border bg-white p-5"><h2 className="mb-4 font-semibold">Create custom role</h2><input required className="mb-3 w-full rounded border px-3 py-2" placeholder="Role name" value={newRole.name} onChange={e=>setNewRole({...newRole,name:e.target.value})}/><input className="mb-3 w-full rounded border px-3 py-2" placeholder="Description" value={newRole.description} onChange={e=>setNewRole({...newRole,description:e.target.value})}/><div className="max-h-72 space-y-2 overflow-auto rounded border p-3">{permissions.map(p=><label key={p.id} className="flex gap-2 text-sm"><input type="checkbox" checked={newRole.permission_ids.includes(p.id)} onChange={e=>setNewRole({...newRole,permission_ids:e.target.checked?[...newRole.permission_ids,p.id]:newRole.permission_ids.filter(id=>id!==p.id)})}/><span><b>{p.name}</b>{p.description&&<span className="block text-gray-500">{p.description}</span>}</span></label>)}</div><button className="mt-3 w-full rounded bg-blue-600 px-4 py-2 text-white">Create Role</button></form><div className="space-y-3">{roles.map(r=><div key={r.id} className="rounded-lg border bg-white p-4"><div className="flex justify-between"><div><div className="font-semibold">{r.name}</div><div className="text-sm text-gray-500">{r.description}</div></div><span className="text-sm">{r.is_active?'Active':'Inactive'}</span></div><div className="mt-3 flex flex-wrap gap-2">{r.permissions.map(p=><span key={p.id} className="rounded bg-gray-100 px-2 py-1 text-xs">{p.name}</span>)}</div></div>)}</div></div>}
      {tab==='audit'&&<div className="overflow-x-auto rounded-lg border bg-white"><table className="min-w-full text-sm"><thead className="bg-gray-50"><tr><th className="p-3 text-left">Time</th><th className="p-3 text-left">User</th><th className="p-3 text-left">Action</th><th className="p-3 text-left">Entity</th><th className="p-3 text-left">Changes</th></tr></thead><tbody>{audits.map(a=><tr key={a.id} className="border-t align-top"><td className="p-3 whitespace-nowrap">{new Date(a.timestamp).toLocaleString()}</td><td className="p-3">{a.user_name||a.user_id||'System'}</td><td className="p-3 font-medium">{a.action}</td><td className="p-3">{a.entity_type||'-'}{a.entity_id?` #${a.entity_id}`:''}</td><td className="max-w-xl p-3 text-xs text-gray-600"><div>{a.old_value&&`Before: ${a.old_value}`}</div><div>{a.new_value&&`After: ${a.new_value}`}</div></td></tr>)}</tbody></table></div>}
      {tab==='controls'&&controls&&<form onSubmit={saveControls} className="max-w-2xl rounded-lg border bg-white p-6"><h2 className="mb-4 font-semibold">Business controls</h2><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm">Invoice prefix<input className="mt-1 w-full rounded border px-3 py-2" value={controls.invoice_prefix||''} onChange={e=>setControls({...controls,invoice_prefix:e.target.value})}/></label><label className="text-sm">Next invoice number<input disabled className="mt-1 w-full rounded border bg-gray-100 px-3 py-2" value={controls.next_invoice_number}/></label><label className="text-sm">Default payment mode<select className="mt-1 w-full rounded border px-3 py-2" value={controls.default_payment_mode||'CREDIT'} onChange={e=>setControls({...controls,default_payment_mode:e.target.value})}><option>CREDIT</option><option>CASH</option><option>UPI</option><option>CARD</option><option>BANK</option></select></label><label className="text-sm">Currency<input className="mt-1 w-full rounded border px-3 py-2" value={controls.currency||'INR'} onChange={e=>setControls({...controls,currency:e.target.value})}/></label><label className="text-sm sm:col-span-2">Invoice template<select className="mt-1 w-full rounded border px-3 py-2" value={controls.selected_invoice_template||'PHARMA_A4'} onChange={e=>setControls({...controls,selected_invoice_template:e.target.value})}><option value="PHARMA_A4">Pharma A4 Tax Invoice</option><option value="COMPACT_RECEIPT">Compact Receipt</option></select></label></div><button className="mt-5 rounded bg-blue-600 px-5 py-2 text-white">Save Controls</button></form>}
    </>}
  </div></div>
}
