import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { apiClient, CompanyDocumentProfile } from '@/services/api'

type FormState={
 company_address:string;company_city:string;company_state:string;company_state_code:string;company_pincode:string;company_phone:string;company_email:string;company_gstin:string;
 drug_license_20b:string;drug_license_21b:string;bank_name:string;bank_account_number:string;bank_branch:string;bank_ifsc:string;invoice_terms:string;jurisdiction:string;authorized_signatory:string;selected_invoice_template:string
}
const blank:FormState={company_address:'',company_city:'',company_state:'',company_state_code:'',company_pincode:'',company_phone:'',company_email:'',company_gstin:'',drug_license_20b:'',drug_license_21b:'',bank_name:'',bank_account_number:'',bank_branch:'',bank_ifsc:'',invoice_terms:'',jurisdiction:'',authorized_signatory:'',selected_invoice_template:'PHARMA_A4'}

export default function DocumentSettings(){
 const [company,setCompany]=useState<CompanyDocumentProfile|null>(null);const [form,setForm]=useState<FormState>(blank);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState('');const [success,setSuccess]=useState('')
 useEffect(()=>{apiClient.getDocumentSettings().then(p=>{setCompany(p);setForm({company_address:p.address||'',company_city:p.city||'',company_state:p.state||'',company_state_code:p.state_code||'',company_pincode:p.pincode||'',company_phone:p.phone||'',company_email:p.email||'',company_gstin:p.gstin||'',drug_license_20b:p.drug_license_20b||'',drug_license_21b:p.drug_license_21b||'',bank_name:p.bank_name||'',bank_account_number:p.bank_account_number||'',bank_branch:p.bank_branch||'',bank_ifsc:p.bank_ifsc||'',invoice_terms:p.invoice_terms||'',jurisdiction:p.jurisdiction||'',authorized_signatory:p.authorized_signatory||'',selected_invoice_template:p.selected_invoice_template||'PHARMA_A4'})}).catch((e:any)=>setError(e?.response?.data?.detail||'Unable to load invoice settings')).finally(()=>setLoading(false))},[])
 const change=(k:keyof FormState,v:string)=>setForm(f=>({...f,[k]:v}))
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);setError('');setSuccess('');try{const p=await apiClient.updateDocumentSettings(form);setCompany(p);setSuccess('Invoice and print settings saved.')}catch(e:any){setError(e?.response?.data?.detail||'Unable to save settings')}finally{setSaving(false)}}
 if(loading)return <div className="p-8 text-center">Loading document settings...</div>
 return <div className="min-h-screen bg-gray-50 p-6"><div className="mx-auto max-w-5xl"><div className="mb-6 flex items-center justify-between"><div><h1 className="text-2xl font-bold">Invoice & Print Settings</h1><p className="text-sm text-gray-500">Configure statutory, bank and footer details shown on MediBill tax invoices and receipts.</p></div><Link to="/dashboard" className="rounded border bg-white px-4 py-2">Dashboard</Link></div>
  {company&&<div className="mb-4 rounded border bg-white p-4"><div className="font-semibold">{company.legal_name||company.company_name}</div><div className="text-sm text-gray-500">These settings are company-specific and are used for every invoice print/reprint.</div></div>}
  {error&&<div className="mb-4 rounded border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}{success&&<div className="mb-4 rounded border border-green-200 bg-green-50 p-3 text-sm text-green-700">{success}</div>}
  <form onSubmit={submit} className="rounded-lg bg-white p-6 shadow-sm"><Section title="Business & statutory details"><div className="grid gap-3 md:grid-cols-2"><Field label="Address" value={form.company_address} onChange={v=>change('company_address',v)}/><Field label="City" value={form.company_city} onChange={v=>change('company_city',v)}/><Field label="State" value={form.company_state} onChange={v=>change('company_state',v)}/><Field label="State code" value={form.company_state_code} onChange={v=>change('company_state_code',v)}/><Field label="Pincode" value={form.company_pincode} onChange={v=>change('company_pincode',v)}/><Field label="Phone" value={form.company_phone} onChange={v=>change('company_phone',v)}/><Field label="Email" value={form.company_email} onChange={v=>change('company_email',v)}/><Field label="GSTIN" value={form.company_gstin} onChange={v=>change('company_gstin',v)}/><Field label="Drug Licence 20B" value={form.drug_license_20b} onChange={v=>change('drug_license_20b',v)}/><Field label="Drug Licence 21B" value={form.drug_license_21b} onChange={v=>change('drug_license_21b',v)}/></div></Section>
  <Section title="Bank details"><div className="grid gap-3 md:grid-cols-2"><Field label="Bank name" value={form.bank_name} onChange={v=>change('bank_name',v)}/><Field label="Account number" value={form.bank_account_number} onChange={v=>change('bank_account_number',v)}/><Field label="Branch" value={form.bank_branch} onChange={v=>change('bank_branch',v)}/><Field label="IFSC" value={form.bank_ifsc} onChange={v=>change('bank_ifsc',v)}/></div></Section>
  <Section title="Invoice footer"><div className="grid gap-3 md:grid-cols-2"><Field label="Jurisdiction" value={form.jurisdiction} onChange={v=>change('jurisdiction',v)}/><Field label="Authorized signatory" value={form.authorized_signatory} onChange={v=>change('authorized_signatory',v)}/><label className="md:col-span-2"><span className="mb-1 block text-sm font-medium">Terms & Conditions</span><textarea rows={5} value={form.invoice_terms} onChange={e=>change('invoice_terms',e.target.value)} className="w-full rounded border px-3 py-2" placeholder={'1) Goods once sold...\n2) Expiry returns as per company policy...'} /></label><label><span className="mb-1 block text-sm font-medium">Default template</span><select value={form.selected_invoice_template} onChange={e=>change('selected_invoice_template',e.target.value)} className="w-full rounded border px-3 py-2"><option value="PHARMA_A4">Pharma A4 Tax Invoice</option><option value="COMPACT_RECEIPT">Compact Order-style Receipt</option></select></label></div></Section>
  <div className="mt-6 text-right"><button disabled={saving} className="rounded bg-blue-700 px-5 py-2 text-white disabled:opacity-50">{saving?'Saving...':'Save Invoice Settings'}</button></div></form>
 </div></div>
}
function Section({title,children}:{title:string;children:React.ReactNode}){return <section className="mb-6"><h2 className="mb-3 border-b pb-2 text-lg font-semibold">{title}</h2>{children}</section>}
function Field({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label><span className="mb-1 block text-sm font-medium">{label}</span><input value={value} onChange={e=>onChange(e.target.value)} className="w-full rounded border px-3 py-2" /></label>}
