import { useEffect, useMemo, useState } from 'react'
import { apiClient, PurchaseInvoice, Supplier } from '@/services/api'

type Product={id:number;product_name:string;product_code:string;gst_rate?:string|number;default_mrp?:string|number;default_selling_price?:string|number}
type Line={product_id:string;batch_number:string;manufacturing_date:string;expiry_date:string;quantity:string;mrp:string;purchase_rate:string;discount_percent:string;gst_rate:string}
const blankLine=():Line=>({product_id:'',batch_number:'',manufacturing_date:'',expiry_date:'',quantity:'1',mrp:'',purchase_rate:'',discount_percent:'0',gst_rate:'0'})
const money=(n:number)=>n.toFixed(2)

export default function Purchases(){
 const [suppliers,setSuppliers]=useState<Supplier[]>([]); const [products,setProducts]=useState<Product[]>([]); const [invoices,setInvoices]=useState<PurchaseInvoice[]>([])
 const [supplierId,setSupplierId]=useState(''); const [purchaseNumber,setPurchaseNumber]=useState(''); const [purchaseDate,setPurchaseDate]=useState(new Date().toISOString().slice(0,10)); const [taxMode,setTaxMode]=useState('INTRA_STATE'); const [notes,setNotes]=useState(''); const [lines,setLines]=useState<Line[]>([blankLine()])
 const [supplierForm,setSupplierForm]=useState({supplier_code:'',supplier_name:'',phone:'',email:'',gstin:'',credit_days:'30'}); const [showSupplier,setShowSupplier]=useState(false); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState(''); const [success,setSuccess]=useState('')
 const load=async()=>{setLoading(true);setError('');try{const [s,p,i]=await Promise.all([apiClient.listSuppliers(),apiClient.listMasterData('products'),apiClient.listPurchases()]);setSuppliers(s);setProducts(p);setInvoices(i)}catch(e:any){setError(e?.response?.data?.detail||'Unable to load purchases')}finally{setLoading(false)}}
 useEffect(()=>{load()},[])
 const totals=useMemo(()=>lines.reduce((a,l)=>{const gross=Number(l.quantity||0)*Number(l.purchase_rate||0);const disc=gross*Number(l.discount_percent||0)/100;const taxable=gross-disc;const gst=taxable*Number(l.gst_rate||0)/100;return {subtotal:a.subtotal+gross,discount:a.discount+disc,taxable:a.taxable+taxable,tax:a.tax+gst,total:a.total+taxable+gst}}, {subtotal:0,discount:0,taxable:0,tax:0,total:0}),[lines])
 const update=(i:number,key:keyof Line,value:string)=>setLines(ls=>ls.map((l,n)=>n===i?{...l,[key]:value}:l))
 const chooseProduct=(i:number,id:string)=>{const p=products.find(x=>String(x.id)===id);update(i,'product_id',id);if(p){update(i,'gst_rate',String(p.gst_rate??0));update(i,'mrp',String(p.default_mrp??''))}}
 const submitSupplier=async(e:React.FormEvent)=>{e.preventDefault();setError('');try{await apiClient.createSupplier({...supplierForm,credit_days:Number(supplierForm.credit_days)});setShowSupplier(false);setSupplierForm({supplier_code:'',supplier_name:'',phone:'',email:'',gstin:'',credit_days:'30'});await load()}catch(e:any){setError(e?.response?.data?.detail||'Unable to create supplier')}}
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);setError('');setSuccess('');try{if(!supplierId)throw new Error('Select a supplier');if(lines.some(l=>!l.product_id||!l.batch_number||!l.expiry_date||!l.quantity||!l.mrp||!l.purchase_rate))throw new Error('Complete every purchase line');const inv=await apiClient.createPurchase({purchase_number:purchaseNumber,purchase_date:purchaseDate,supplier_id:Number(supplierId),tax_mode:taxMode,notes,items:lines.map(l=>({...l,product_id:Number(l.product_id),quantity:Number(l.quantity),mrp:Number(l.mrp),purchase_rate:Number(l.purchase_rate),discount_percent:Number(l.discount_percent||0),gst_rate:Number(l.gst_rate||0)}))});setSuccess(`Purchase ${inv.purchase_number} posted. Inventory increased automatically.`);setPurchaseNumber('');setNotes('');setLines([blankLine()]);await load()}catch(e:any){setError(e?.response?.data?.detail||e.message||'Unable to post purchase')}finally{setSaving(false)}}
 return <div className="min-h-screen bg-gray-50 p-6"><div className="mx-auto max-w-7xl">
  <div className="mb-6 flex items-center justify-between"><div><h1 className="text-2xl font-bold text-gray-900">Purchases & Suppliers</h1><p className="text-sm text-gray-500">Post supplier purchases and automatically receive stock into batches.</p></div><button onClick={()=>setShowSupplier(true)} className="rounded bg-gray-900 px-4 py-2 text-white">+ Supplier</button></div>
  {error&&<div className="mb-4 rounded border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}{success&&<div className="mb-4 rounded border border-green-200 bg-green-50 p-3 text-sm text-green-700">{success}</div>}
  <form onSubmit={submit} className="mb-8 rounded-lg bg-white p-5 shadow-sm"><div className="mb-4 grid gap-3 md:grid-cols-4"><select required value={supplierId} onChange={e=>setSupplierId(e.target.value)} className="rounded border px-3 py-2"><option value="">Select supplier</option>{suppliers.map(s=><option key={s.id} value={s.id}>{s.supplier_name} ({s.supplier_code})</option>)}</select><input required placeholder="Purchase number" value={purchaseNumber} onChange={e=>setPurchaseNumber(e.target.value)} className="rounded border px-3 py-2"/><input required type="date" value={purchaseDate} onChange={e=>setPurchaseDate(e.target.value)} className="rounded border px-3 py-2"/><select value={taxMode} onChange={e=>setTaxMode(e.target.value)} className="rounded border px-3 py-2"><option value="INTRA_STATE">CGST + SGST</option><option value="INTER_STATE">IGST</option></select></div>
   <div className="overflow-x-auto"><table className="min-w-[1100px] w-full text-sm"><thead><tr className="border-b text-left">{['Product','Batch','Mfg','Expiry','Qty','MRP','Rate','Disc %','GST %','Amount',''].map(h=><th className="p-2" key={h}>{h}</th>)}</tr></thead><tbody>{lines.map((l,i)=>{const amount=Number(l.quantity||0)*Number(l.purchase_rate||0)*(1-Number(l.discount_percent||0)/100)*(1+Number(l.gst_rate||0)/100);return <tr key={i} className="border-b"><td className="p-2"><select required value={l.product_id} onChange={e=>chooseProduct(i,e.target.value)} className="w-44 rounded border px-2 py-2"><option value="">Product</option>{products.map(p=><option key={p.id} value={p.id}>{p.product_name} ({p.product_code})</option>)}</select></td><td className="p-2"><input required value={l.batch_number} onChange={e=>update(i,'batch_number',e.target.value)} placeholder="Batch" className="w-28 rounded border px-2 py-2"/></td><td className="p-2"><input type="date" value={l.manufacturing_date} onChange={e=>update(i,'manufacturing_date',e.target.value)} className="w-32 rounded border px-2 py-2"/></td><td className="p-2"><input required type="date" value={l.expiry_date} onChange={e=>update(i,'expiry_date',e.target.value)} className="w-32 rounded border px-2 py-2"/></td><td className="p-2"><input required type="number" min="1" value={l.quantity} onChange={e=>update(i,'quantity',e.target.value)} className="w-20 rounded border px-2 py-2"/></td><td className="p-2"><input required type="number" min="0" step="0.01" value={l.mrp} onChange={e=>update(i,'mrp',e.target.value)} className="w-24 rounded border px-2 py-2"/></td><td className="p-2"><input required type="number" min="0" step="0.01" value={l.purchase_rate} onChange={e=>update(i,'purchase_rate',e.target.value)} className="w-24 rounded border px-2 py-2"/></td><td className="p-2"><input type="number" min="0" max="100" step="0.01" value={l.discount_percent} onChange={e=>update(i,'discount_percent',e.target.value)} className="w-20 rounded border px-2 py-2"/></td><td className="p-2"><input type="number" min="0" max="100" step="0.01" value={l.gst_rate} onChange={e=>update(i,'gst_rate',e.target.value)} className="w-20 rounded border px-2 py-2"/></td><td className="p-2 font-medium">{money(amount)}</td><td className="p-2"><button type="button" disabled={lines.length===1} onClick={()=>setLines(ls=>ls.filter((_,n)=>n!==i))} className="text-red-600 disabled:text-gray-300">Remove</button></td></tr>})}</tbody></table></div>
   <div className="mt-3 flex justify-between"><button type="button" onClick={()=>setLines(ls=>[...ls,blankLine()])} className="rounded border px-4 py-2">+ Add line</button><div className="text-right text-sm"><div>Subtotal: ₹{money(totals.subtotal)}</div><div>Discount: ₹{money(totals.discount)}</div><div>Taxable: ₹{money(totals.taxable)}</div><div>GST: ₹{money(totals.tax)}</div><div className="text-lg font-bold">Grand total: ₹{money(totals.total)}</div></div></div>
   <textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Notes (optional)" className="mt-4 w-full rounded border px-3 py-2" rows={2}/><div className="mt-4 text-right"><button disabled={saving} className="rounded bg-blue-600 px-5 py-2 text-white disabled:opacity-50">{saving?'Posting...':'Post Purchase & Receive Stock'}</button></div>
  </form>
  <div className="rounded-lg bg-white shadow-sm"><div className="border-b p-4 font-semibold">Purchase history</div>{loading?<div className="p-6 text-center text-gray-500">Loading...</div>:invoices.length===0?<div className="p-6 text-center text-gray-500">No purchases yet.</div>:<div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="border-b bg-gray-50"><tr><th className="p-3 text-left">Date</th><th className="p-3 text-left">Purchase #</th><th className="p-3 text-left">Supplier</th><th className="p-3 text-right">Total</th><th className="p-3 text-left">Status</th></tr></thead><tbody>{invoices.map(i=><tr key={i.id} className="border-b"><td className="p-3">{i.purchase_date}</td><td className="p-3 font-medium">{i.purchase_number}</td><td className="p-3">{i.supplier_name}</td><td className="p-3 text-right">₹{i.grand_total}</td><td className="p-3">{i.payment_status}</td></tr>)}</tbody></table></div>}</div>
  {showSupplier&&<div className="fixed inset-0 flex items-center justify-center bg-black/40 p-4"><form onSubmit={submitSupplier} className="w-full max-w-lg rounded-lg bg-white p-6 shadow-xl"><h2 className="mb-4 text-lg font-semibold">Add Supplier</h2><div className="grid gap-3"><input required placeholder="Supplier code" value={supplierForm.supplier_code} onChange={e=>setSupplierForm({...supplierForm,supplier_code:e.target.value})} className="rounded border px-3 py-2"/><input required placeholder="Supplier name" value={supplierForm.supplier_name} onChange={e=>setSupplierForm({...supplierForm,supplier_name:e.target.value})} className="rounded border px-3 py-2"/><input placeholder="Phone" value={supplierForm.phone} onChange={e=>setSupplierForm({...supplierForm,phone:e.target.value})} className="rounded border px-3 py-2"/><input type="email" placeholder="Email" value={supplierForm.email} onChange={e=>setSupplierForm({...supplierForm,email:e.target.value})} className="rounded border px-3 py-2"/><input placeholder="GSTIN" value={supplierForm.gstin} onChange={e=>setSupplierForm({...supplierForm,gstin:e.target.value})} className="rounded border px-3 py-2"/><input type="number" min="0" placeholder="Credit days" value={supplierForm.credit_days} onChange={e=>setSupplierForm({...supplierForm,credit_days:e.target.value})} className="rounded border px-3 py-2"/></div><div className="mt-5 flex justify-end gap-2"><button type="button" onClick={()=>setShowSupplier(false)} className="rounded border px-4 py-2">Cancel</button><button className="rounded bg-gray-900 px-4 py-2 text-white">Create supplier</button></div></form></div>}
 </div></div>
}
