import React, { useState } from 'react'
import { useNavigate, Link } from 'react-router-dom'
import { useAuth } from '@/context/AuthContext'

export default function Register(){
 const navigate=useNavigate();const{register,isLoading,error}=useAuth();const[formData,setFormData]=useState({name:'',email:'',password:'',confirmPassword:'',companyName:'',mobile:''});const[show,setShow]=useState(false);const[localError,setLocalError]=useState('')
 const handleChange=(e:React.ChangeEvent<HTMLInputElement>)=>{const{name,value}=e.target;setFormData(p=>({...p,[name]:value}))}
 const handleSubmit=async(e:React.FormEvent)=>{e.preventDefault();setLocalError('');if(formData.password.length<8){setLocalError('Password must be at least 8 characters');return}if(!/[A-Za-z]/.test(formData.password)||!/[0-9]/.test(formData.password)){setLocalError('Password must contain at least one letter and one number');return}if(formData.password!==formData.confirmPassword){setLocalError('Passwords do not match');return}try{await register(formData.name,formData.email,formData.password,formData.companyName,formData.mobile);navigate('/dashboard')}catch(err:any){setLocalError(err.message)}}
 const field=(name:string,label:string,type='text',placeholder='')=><div><label className="block text-sm font-medium text-gray-700">{label}</label><input type={type} name={name} value={(formData as any)[name]} onChange={handleChange} required={!label.includes('optional')} className="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md" placeholder={placeholder}/></div>
 return <div className="min-h-screen flex items-center justify-center bg-gray-50 py-12 px-4"><div className="max-w-md w-full bg-white rounded-lg shadow-md p-8"><div className="text-center mb-6"><h1 className="text-3xl font-bold">MediBill</h1><p className="text-gray-600 mt-2">Medical Agency Billing System</p></div><h2 className="text-xl font-bold mb-6 text-center">Create Account</h2>{(error||localError)&&<div className="mb-4 p-3 bg-red-100 text-red-700 rounded">{localError||error}</div>}<form onSubmit={handleSubmit} className="space-y-4">{field('name','Full Name','text','John Doe')}{field('email','Email','email','you@example.com')}<div><label className="block text-sm font-medium">Password</label><input type={show?'text':'password'} name="password" value={formData.password} onChange={handleChange} required className="mt-1 w-full px-3 py-2 border rounded-md"/><p className="text-xs text-gray-500 mt-1">At least 8 characters with one letter and one number.</p></div><div><label className="block text-sm font-medium">Confirm Password</label><input type={show?'text':'password'} name="confirmPassword" value={formData.confirmPassword} onChange={handleChange} required className="mt-1 w-full px-3 py-2 border rounded-md"/></div><label className="flex gap-2 text-sm text-gray-600"><input type="checkbox" checked={show} onChange={e=>setShow(e.target.checked)}/> Show passwords</label>{field('companyName','Company Name','text','ABC Pharma')}{field('mobile','Mobile (optional)','tel','+91 9876543210')}<button type="submit" disabled={isLoading} className="w-full px-4 py-2 bg-blue-600 text-white rounded-md disabled:bg-gray-400">{isLoading?'Creating account...':'Register'}</button></form><p className="mt-4 text-center text-sm text-gray-600">Already have an account? <Link to="/login" className="text-blue-600">Login here</Link></p></div></div>
}
