import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { apiClient, CustomerPerformanceRow, InventoryIntelligenceRow, ProductPerformanceRow, PurchaseRegisterRow, SalesRegisterRow } from '@/services/api'

type Tab='inventory'|'sales'|'purchases'|'products'|'customers'
const today=()=>new Date().toISOString().slice(0,10)
const monthStart=()=>{const d=new Date();d.setDate(1);return d.toISOString().slice(0,10)}
const rupees=(v:string|number)=>`₹${Number(v||0).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})}`

function downloadCsv(name:string, rows:Record<string,unknown>[]){
 if(!rows.length)return
 const keys=Object.keys(rows[0]); const esc=(v:unknown)=>`"${String(v??'').replace(/"/g,'""')}"`
 const csv=[keys.map(esc).join(','),...rows.map(r=>keys.map(k=>esc(r[k])).join(','))].join('\n')
 const blob=new Blob([csv],{type:'text/csv;charset=utf-8;'}); const url=URL.createObjectURL(blob); const a=document.createElement('a'); a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)
}

export default function Reports(){
 const [tab,setTab]=useState<Tab>('inventory'); const [fromDate,setFromDate]=useState(monthStart()); const [toDate,setToDate]=useState(today()); const [loading,setLoading]=useState(false); const [error,setError]=useState('')
 const [inventory,setInventory]=useState<InventoryIntelligenceRow[]>([]); const [sales,setSales]=useState<SalesRegisterRow[]>([]); const [purchases,setPurchases]=useState<PurchaseRegisterRow[]>([]); const [products,setProducts]=useState<ProductPerformanceRow[]>([]); const [customers,setCustomers]=useState<CustomerPerformanceRow[]>([])
 const [movement,setMovement]=useState('ALL'); const [search,setSearch]=useState('')
 const load=async()=>{setLoading(true);setError('');try{const params={from_date:fromDate,to_date:toDate};const [i,s,p,tp,tc]=await Promise.all([apiClient.getInventoryIntelligence(false),apiClient.getSalesRegister(params),apiClient.getPurchaseRegister(params),apiClient.getTopProducts(params),apiClient.getTopCustomers(params)]);setInventory(i);setSales(s);setPurchases(p);setProducts(tp);setCustomers(tc)}catch(e:any){setError(e?.response?.data?.detail||'Unable to load reports')}finally{setLoading(false)}}
 useEffect(()=>{load()},[])
 const filteredInventory=useMemo(()=>inventory.filter(r=>(movement==='ALL'||r.movement_class===movement)&&(!search||`${r.product_code} ${r.product_name} ${r.batch_number}`.toLowerCase().includes(search.toLowerCase()))),[inventory,movement,search])
 const stockValue=inventory.reduce((a,r)=>a+Number(r.stock_value||0),0); const reorderCount=new Set(inventory.filter(r=>r.reorder_suggested>0).map(r=>r.product_id)).size; const nonMoving=new Set(inventory.filter(r=>r.movement_class==='NON_MOVING').map(r=>r.product_id)).size; const expiryExposure=inventory.filter(r=>r.days_to_expiry<=90).reduce((a,r)=>a+Number(r.stock_value||0),0)
 const tabs:[Tab,string][]=[['inventory','Inventory Intelligence'],['sales','Sales Register'],['purchases','Purchase Register'],['products','Top Products'],['customers','Top Customers']]
 const exportCurrent=()=>{if(tab==='inventory')downloadCsv('inventory-intelligence.csv',filteredInventory as any);if(tab==='sales')downloadCsv('sales-register.csv',sales as any);if(tab==='purchases')downloadCsv('purchase-register.csv',purchases as any);if(tab==='products')downloadCsv('top-products.csv',products as any);if(tab==='customers')downloadCsv('top-customers.csv',customers as any)}
 return <div className="min-h-screen bg-gray-50 p-6"><div className="mx-auto max-w-7xl">
  <div className="mb-5 flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold">Advanced Inventory & Business Reports</h1><p className="text-sm text-gray-500">Stock valuation, movement intelligence, registers, reorder suggestions and sales analytics.</p></div><div className="flex gap-2"><Link to="/dashboard" className="rounded border bg-white px-4 py-2">Dashboard</Link><button onClick={exportCurrent} className="rounded bg-emerald-600 px-4 py-2 text-white">Export CSV</button></div></div>
  {error&&<div className="mb-4 rounded border border-red-200 bg-red-50 p-3 text-red-700">{error}</div>}
  <div className="mb-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Card title="Stock Value" value={rupees(stockValue)}/><Card title="Products to Reorder" value={String(reorderCount)}/><Card title="Non-moving Products" value={String(nonMoving)}/><Card title="≤90 Day Expiry Exposure" value={rupees(expiryExposure)}/></div>
  <div className="mb-4 rounded-lg bg-white p-4 shadow-sm"><div className="flex flex-wrap gap-2">{tabs.map(([k,l])=><button key={k} onClick={()=>setTab(k)} className={`rounded px-3 py-2 text-sm ${tab===k?'bg-blue-600 text-white':'bg-gray-100'}`}>{l}</button>)}</div><div className="mt-4 flex flex-wrap gap-3"><input type="date" value={fromDate} onChange={e=>setFromDate(e.target.value)} className="rounded border px-3 py-2"/><input type="date" value={toDate} onChange={e=>setToDate(e.target.value)} className="rounded border px-3 py-2"/><button onClick={load} className="rounded border bg-white px-4 py-2">Apply Dates</button>{tab==='inventory'&&<><select value={movement} onChange={e=>setMovement(e.target.value)} className="rounded border px-3 py-2"><option>ALL</option><option>FAST</option><option>ACTIVE</option><option>SLOW</option><option>NON_MOVING</option></select><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Product / code / batch" className="min-w-56 rounded border px-3 py-2"/></>}</div></div>
  <div className="rounded-lg bg-white shadow-sm">{loading?<div className="p-8 text-center text-gray-500">Loading reports...</div>:tab==='inventory'?<InventoryTable rows={filteredInventory}/>:tab==='sales'?<SalesTable rows={sales}/>:tab==='purchases'?<PurchaseTable rows={purchases}/>:tab==='products'?<ProductTable rows={products}/>:<CustomerTable rows={customers}/>}</div>
 </div></div>
}
function Card({title,value}:{title:string;value:string}){return <div className="rounded-lg bg-white p-4 shadow-sm"><div className="text-sm text-gray-500">{title}</div><div className="mt-1 text-2xl font-bold">{value}</div></div>}
function InventoryTable({rows}:{rows:InventoryIntelligenceRow[]}){return <div className="overflow-x-auto"><table className="min-w-[1200px] w-full text-sm"><thead className="bg-gray-50"><tr>{['Product','Batch','Expiry','Days','Available','Purchase Rate','Stock Value','30D Sold','Movement','Reorder Level','Total Product Stock','Suggested Reorder'].map(h=><th key={h} className="p-3 text-left">{h}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.batch_id} className="border-t"><td className="p-3"><b>{r.product_name}</b><div className="text-xs text-gray-500">{r.product_code}</div></td><td className="p-3">{r.batch_number}</td><td className="p-3">{r.expiry_date}</td><td className={`p-3 ${r.days_to_expiry<=30?'font-semibold text-red-600':r.days_to_expiry<=90?'text-amber-600':''}`}>{r.days_to_expiry}</td><td className="p-3">{r.quantity_available}</td><td className="p-3">{rupees(r.purchase_rate)}</td><td className="p-3">{rupees(r.stock_value)}</td><td className="p-3">{r.units_sold_30d}</td><td className="p-3"><span className="rounded bg-gray-100 px-2 py-1 text-xs font-semibold">{r.movement_class}</span></td><td className="p-3">{r.reorder_level}</td><td className="p-3">{r.product_available}</td><td className="p-3 font-semibold">{r.reorder_suggested}</td></tr>)}</tbody></table></div>}
function SalesTable({rows}:{rows:SalesRegisterRow[]}){return <div className="overflow-x-auto"><table className="min-w-[1000px] w-full text-sm"><thead className="bg-gray-50"><tr>{['Date','Invoice','Customer','Billed','Free','Taxable','CGST','SGST','IGST','Gross','Returns','Net Sales'].map(h=><th key={h} className="p-3 text-left">{h}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.invoice_id} className="border-t"><td className="p-3">{r.invoice_date}</td><td className="p-3 font-medium">{r.invoice_number}</td><td className="p-3">{r.customer_name}</td><td className="p-3">{r.billed_units}</td><td className="p-3">{r.free_units}</td><td className="p-3">{rupees(r.taxable_total)}</td><td className="p-3">{rupees(r.cgst)}</td><td className="p-3">{rupees(r.sgst)}</td><td className="p-3">{rupees(r.igst)}</td><td className="p-3">{rupees(r.gross_invoice)}</td><td className="p-3">{rupees(r.returns)}</td><td className="p-3 font-semibold">{rupees(r.net_sales)}</td></tr>)}</tbody></table></div>}
function PurchaseTable({rows}:{rows:PurchaseRegisterRow[]}){return <div className="overflow-x-auto"><table className="min-w-[1000px] w-full text-sm"><thead className="bg-gray-50"><tr>{['Date','Purchase #','Supplier','Paid Qty','Free','Taxable','CGST','SGST','IGST','Gross','Returns','Net Purchase'].map(h=><th key={h} className="p-3 text-left">{h}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.invoice_id} className="border-t"><td className="p-3">{r.purchase_date}</td><td className="p-3 font-medium">{r.purchase_number}</td><td className="p-3">{r.supplier_name}</td><td className="p-3">{r.paid_units}</td><td className="p-3">{r.free_units}</td><td className="p-3">{rupees(r.taxable_total)}</td><td className="p-3">{rupees(r.cgst)}</td><td className="p-3">{rupees(r.sgst)}</td><td className="p-3">{rupees(r.igst)}</td><td className="p-3">{rupees(r.gross_purchase)}</td><td className="p-3">{rupees(r.returns)}</td><td className="p-3 font-semibold">{rupees(r.net_purchase)}</td></tr>)}</tbody></table></div>}
function ProductTable({rows}:{rows:ProductPerformanceRow[]}){return <div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-gray-50"><tr>{['Product','Code','Billed Units','Free Units','Sales Value'].map(h=><th key={h} className="p-3 text-left">{h}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.product_id} className="border-t"><td className="p-3 font-medium">{r.product_name}</td><td className="p-3">{r.product_code}</td><td className="p-3">{r.billed_units}</td><td className="p-3">{r.free_units}</td><td className="p-3 font-semibold">{rupees(r.net_sales)}</td></tr>)}</tbody></table></div>}
function CustomerTable({rows}:{rows:CustomerPerformanceRow[]}){return <div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-gray-50"><tr><th className="p-3 text-left">Customer</th><th className="p-3 text-left">Invoices</th><th className="p-3 text-left">Sales Value</th></tr></thead><tbody>{rows.map(r=><tr key={r.customer_id} className="border-t"><td className="p-3 font-medium">{r.customer_name}</td><td className="p-3">{r.invoice_count}</td><td className="p-3 font-semibold">{rupees(r.net_sales)}</td></tr>)}</tbody></table></div>}
