import { FormEvent, useState } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import { apiClient } from '@/services/api'

export default function ResetPassword(){
 const [params]=useSearchParams(); const token=params.get('token')||sessionStorage.getItem('medibill_reset_token')||''; const [password,setPassword]=useState('');const [confirm,setConfirm]=useState('');const [show,setShow]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');const [loading,setLoading]=useState(false)
 const submit=async(e:FormEvent)=>{e.preventDefault();setError('');if(password.length<8){setError('Password must be at least 8 characters');return}if(!/[A-Za-z]/.test(password)||!/[0-9]/.test(password)){setError('Password must contain at least one letter and one number');return}if(password!==confirm){setError('Passwords do not match');return}if(!token){setError('Reset link is missing. Start again from Forgot Password.');return}setLoading(true);try{const r=await apiClient.resetPassword(token,password);sessionStorage.removeItem('medibill_reset_token');setMessage(r.message)}catch(err:any){setError(err.response?.data?.detail||'Unable to reset password')}finally{setLoading(false)}}
 return <div className="min-h-screen flex items-center justify-center bg-gray-50 p-4"><div className="max-w-md w-full bg-white rounded-xl shadow-md p-8"><h1 className="text-3xl font-bold text-center">MediBill</h1><h2 className="text-xl font-semibold mt-7">Create a new password</h2><p className="text-sm text-gray-600 mt-2">Use at least 8 characters with at least one letter and one number. Do not reuse a shared or easily guessed password.</p>{error&&<div className="mt-4 p-3 bg-red-50 text-red-700 rounded text-sm">{error}</div>}{message&&<div className="mt-4 p-3 bg-green-50 text-green-800 rounded text-sm">{message} <Link to="/login" className="font-semibold underline">Login now</Link></div>} {!message&&<form onSubmit={submit} className="mt-5 space-y-4"><div><label className="block text-sm font-medium">New password</label><input type={show?'text':'password'} required value={password} onChange={e=>setPassword(e.target.value)} className="mt-1 w-full px-3 py-2 border rounded-md"/></div><div><label className="block text-sm font-medium">Confirm new password</label><input type={show?'text':'password'} required value={confirm} onChange={e=>setConfirm(e.target.value)} className="mt-1 w-full px-3 py-2 border rounded-md"/></div><label className="flex gap-2 text-sm"><input type="checkbox" checked={show} onChange={e=>setShow(e.target.checked)}/> Show passwords</label><button disabled={loading} className="w-full px-4 py-2 bg-blue-600 text-white rounded-md disabled:bg-gray-400">{loading?'Resetting...':'Reset password'}</button></form>}<p className="mt-5 text-center text-sm"><Link className="text-blue-600" to="/login">Back to login</Link></p></div></div>
}
