import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { apiClient, PurchaseInvoice, SalesInvoice } from '@/services/api'
import { returnsApi, PurchaseReturn, SalesReturn } from '@/services/returnsApi'

type Tab='sales'|'purchases'
const today=()=>new Date().toISOString().slice(0,10)

export default function Returns(){
 const [tab,setTab]=useState<Tab>('sales'); const [sales,setSales]=useState<SalesInvoice[]>([]); const [purchases,setPurchases]=useState<PurchaseInvoice[]>([]); const [salesReturns,setSalesReturns]=useState<SalesReturn[]>([]); const [purchaseReturns,setPurchaseReturns]=useState<PurchaseReturn[]>([])
 const [sourceId,setSourceId]=useState(''); const [returnNumber,setReturnNumber]=useState(''); const [returnDate,setReturnDate]=useState(today()); const [reason,setReason]=useState(''); const [qty,setQty]=useState<Record<number,string>>({}); const [freeQty,setFreeQty]=useState<Record<number,string>>({}); const [disposition,setDisposition]=useState<Record<number,string>>({}); const [error,setError]=useState(''); const [success,setSuccess]=useState(''); const [saving,setSaving]=useState(false)
 const load=async()=>{try{const [s,p,sr,pr]=await Promise.all([apiClient.listSales(),apiClient.listPurchases(),returnsApi.listSalesReturns(),returnsApi.listPurchaseReturns()]);setSales(s);setPurchases(p);setSalesReturns(sr);setPurchaseReturns(pr)}catch(e:any){setError(e?.response?.data?.detail||'Unable to load return data')}}
 useEffect(()=>{load()},[])
 useEffect(()=>{setSourceId('');setQty({});setFreeQty({});setDisposition({});setError('');setSuccess('')},[tab])
 const selectedSale=useMemo(()=>sales.find(x=>String(x.id)===sourceId),[sales,sourceId]); const selectedPurchase=useMemo(()=>purchases.find(x=>String(x.id)===sourceId),[purchases,sourceId])
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);setError('');setSuccess('');try{if(!sourceId||!returnNumber.trim())throw new Error('Select the original invoice and enter a return number');if(tab==='sales'){const items=(selectedSale?.items||[]).filter(i=>Number(qty[i.id]||0)>0).map(i=>({sales_invoice_item_id:i.id,quantity:Number(qty[i.id]),disposition:disposition[i.id]||'SALEABLE',reason:reason||null}));if(!items.length)throw new Error('Enter a return quantity for at least one sales line');const r=await returnsApi.createSalesReturn({return_number:returnNumber.trim(),return_date:returnDate,sales_invoice_id:Number(sourceId),reason:reason||null,items});setSuccess(`Sales return ${r.return_number} posted. Saleable stock was restored to the original batch.`)}else{const items=(selectedPurchase?.items||[]).filter(i=>Number(qty[i.id]||0)>0||Number(freeQty[i.id]||0)>0).map(i=>({purchase_invoice_item_id:i.id,quantity:Number(qty[i.id]||0),free_quantity:Number(freeQty[i.id]||0),reason:reason||null}));if(!items.length)throw new Error('Enter a paid or free return quantity for at least one purchase line');if(items.some(i=>i.quantity<1))throw new Error('A purchase return currently requires at least one paid unit per selected line');const r=await returnsApi.createPurchaseReturn({return_number:returnNumber.trim(),return_date:returnDate,purchase_invoice_id:Number(sourceId),reason:reason||null,items});setSuccess(`Purchase return ${r.return_number} posted. Stock was reduced from the original batch.`)}setReturnNumber('');setReason('');setQty({});setFreeQty({});await load()}catch(e:any){setError(e?.response?.data?.detail||e.message||'Unable to post return')}finally{setSaving(false)}}
 return <div className="min-h-screen bg-gray-50 p-6"><div className="mx-auto max-w-7xl"><div className="mb-6 flex items-center justify-between"><div><h1 className="text-2xl font-bold">Returns & Adjustments</h1><p className="text-sm text-gray-500">Return against the original invoice, product and batch for full pharma traceability.</p></div><Link to="/dashboard" className="rounded bg-gray-900 px-4 py-2 text-white">Dashboard</Link></div>
 <div className="mb-4 flex gap-2"><button onClick={()=>setTab('sales')} className={`rounded px-4 py-2 ${tab==='sales'?'bg-blue-600 text-white':'bg-white border'}`}>Sales Returns</button><button onClick={()=>setTab('purchases')} className={`rounded px-4 py-2 ${tab==='purchases'?'bg-blue-600 text-white':'bg-white border'}`}>Purchase Returns</button></div>
 {error&&<div className="mb-4 rounded border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}{success&&<div className="mb-4 rounded border border-green-200 bg-green-50 p-3 text-sm text-green-700">{success}</div>}
 <form onSubmit={submit} className="rounded-lg bg-white p-5 shadow-sm"><div className="grid gap-3 md:grid-cols-4"><select required value={sourceId} onChange={e=>{setSourceId(e.target.value);setQty({});setFreeQty({})}} className="rounded border px-3 py-2"><option value="">Original {tab==='sales'?'sales':'purchase'} invoice</option>{(tab==='sales'?sales:purchases).map((x:any)=><option key={x.id} value={x.id}>{tab==='sales'?x.invoice_number:x.purchase_number} · {tab==='sales'?x.customer_name:x.supplier_name}</option>)}</select><input required value={returnNumber} onChange={e=>setReturnNumber(e.target.value)} placeholder="Return number" className="rounded border px-3 py-2"/><input required type="date" value={returnDate} max={today()} onChange={e=>setReturnDate(e.target.value)} className="rounded border px-3 py-2"/><input value={reason} onChange={e=>setReason(e.target.value)} placeholder="Return reason" className="rounded border px-3 py-2"/></div>
 {tab==='sales'&&selectedSale&&<div className="mt-5 overflow-x-auto"><table className="min-w-full text-sm"><thead><tr className="border-b">{['Product','Batch','Sold Qty','Return Qty','Condition'].map(h=><th key={h} className="p-2 text-left">{h}</th>)}</tr></thead><tbody>{selectedSale.items.map(i=><tr key={i.id} className="border-b"><td className="p-2">{i.product_name}</td><td className="p-2">{i.batch_number}</td><td className="p-2">{i.quantity}</td><td className="p-2"><input type="number" min="0" max={i.quantity} value={qty[i.id]||''} onChange={e=>setQty({...qty,[i.id]:e.target.value})} className="w-24 rounded border px-2 py-1"/></td><td className="p-2"><select value={disposition[i.id]||'SALEABLE'} onChange={e=>setDisposition({...disposition,[i.id]:e.target.value})} className="rounded border px-2 py-1"><option value="SALEABLE">Saleable</option><option value="DAMAGED">Damaged</option><option value="EXPIRED">Expired</option></select></td></tr>)}</tbody></table></div>}
 {tab==='purchases'&&selectedPurchase&&<div className="mt-5 overflow-x-auto"><table className="min-w-full text-sm"><thead><tr className="border-b">{['Product','Batch','Paid Qty','Free Qty','Return Paid','Return Free'].map(h=><th key={h} className="p-2 text-left">{h}</th>)}</tr></thead><tbody>{selectedPurchase.items.map(i=><tr key={i.id} className="border-b"><td className="p-2">{i.product_name}</td><td className="p-2">{i.batch_number}</td><td className="p-2">{i.quantity}</td><td className="p-2">{i.free_quantity||0}</td><td className="p-2"><input type="number" min="0" max={i.quantity} value={qty[i.id]||''} onChange={e=>setQty({...qty,[i.id]:e.target.value})} className="w-24 rounded border px-2 py-1"/></td><td className="p-2"><input type="number" min="0" max={i.free_quantity||0} value={freeQty[i.id]||''} onChange={e=>setFreeQty({...freeQty,[i.id]:e.target.value})} className="w-24 rounded border px-2 py-1"/></td></tr>)}</tbody></table></div>}
 <div className="mt-5 text-right"><button disabled={saving||!sourceId} className="rounded bg-blue-600 px-5 py-2 text-white disabled:opacity-50">{saving?'Posting...':`Post ${tab==='sales'?'Sales':'Purchase'} Return`}</button></div></form>
 <div className="mt-8 rounded-lg bg-white shadow-sm"><div className="border-b p-4 font-semibold">Recent {tab==='sales'?'sales':'purchase'} returns</div><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead><tr className="border-b bg-gray-50"><th className="p-3 text-left">Date</th><th className="p-3 text-left">Return #</th><th className="p-3 text-left">Original Invoice ID</th><th className="p-3 text-right">Return Value</th></tr></thead><tbody>{(tab==='sales'?salesReturns:purchaseReturns).map((r:any)=><tr key={r.id} className="border-b"><td className="p-3">{r.return_date}</td><td className="p-3 font-medium">{r.return_number}</td><td className="p-3">{tab==='sales'?r.sales_invoice_id:r.purchase_invoice_id}</td><td className="p-3 text-right">₹{r.grand_total}</td></tr>)}</tbody></table></div></div>
 </div></div>
}
