import { useEffect, useMemo, useState } from 'react'
import { apiClient, SalesInvoice } from '@/services/api'
import { inventoryApi } from '@/services/inventoryApi'

type Customer={id:number;customer_name:string;customer_code:string;gstin?:string;state?:string;is_active:boolean}
type Product={id:number;product_name:string;product_code:string;gst_rate?:string|number;default_selling_price?:string|number}
type Batch={id:number;product_id:number;batch_number:string;expiry_date:string;mrp:string|number;is_active:boolean}
type Stock={batch_id:number;product_id:number;quantity_available:number;batch_number:string;expiry_date:string}
type Line={product_id:string;batch_id:string;quantity:string;selling_price:string;discount_percent:string;gst_rate:string}

const blankLine=():Line=>({product_id:'',batch_id:'',quantity:'1',selling_price:'',discount_percent:'0',gst_rate:'0'})
const money=(n:number)=>n.toFixed(2)

export default function Sales(){
 const [customers,setCustomers]=useState<Customer[]>([]); const [products,setProducts]=useState<Product[]>([]); const [batches,setBatches]=useState<Batch[]>([]); const [stock,setStock]=useState<Stock[]>([]); const [invoices,setInvoices]=useState<SalesInvoice[]>([])
 const [customerId,setCustomerId]=useState(''); const [invoiceNumber,setInvoiceNumber]=useState(''); const [invoiceDate,setInvoiceDate]=useState(new Date().toISOString().slice(0,10)); const [taxMode,setTaxMode]=useState('INTRA_STATE'); const [paymentMode,setPaymentMode]=useState('CREDIT'); const [amountPaid,setAmountPaid]=useState('0'); const [paymentReference,setPaymentReference]=useState(''); const [notes,setNotes]=useState(''); const [lines,setLines]=useState<Line[]>([blankLine()])
 const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState(''); const [success,setSuccess]=useState('');

 const load=async()=>{setLoading(true);setError('');try{const [c,p,b,s,i]=await Promise.all([apiClient.listMasterData('customers'),apiClient.listMasterData('products'),inventoryApi.listBatches(),inventoryApi.listStock(undefined,false),apiClient.listSales()]);setCustomers(c);setProducts(p);setBatches(b);setStock(s);setInvoices(i)}catch(e:any){setError(e?.response?.data?.detail||'Unable to load billing data')}finally{setLoading(false)}}
 useEffect(()=>{load()},[])

 const totals=useMemo(()=>lines.reduce((a,l)=>{const gross=Number(l.quantity||0)*Number(l.selling_price||0);const disc=gross*Number(l.discount_percent||0)/100;const taxable=gross-disc;const gst=taxable*Number(l.gst_rate||0)/100;return {subtotal:a.subtotal+gross,discount:a.discount+disc,taxable:a.taxable+taxable,tax:a.tax+gst,total:a.total+taxable+gst}}, {subtotal:0,discount:0,taxable:0,tax:0,total:0}),[lines])
 const update=(i:number,key:keyof Line,value:string)=>setLines(ls=>ls.map((l,n)=>n===i?{...l,[key]:value}:l))
 const productBatches=(productId:string)=>batches.filter(b=>String(b.product_id)===productId&&b.is_active&&new Date(b.expiry_date)>=new Date(invoiceDate)&&((stock.find(s=>s.batch_id===b.id)?.quantity_available)||0)>0)
 const chooseProduct=(i:number,id:string)=>{const p=products.find(x=>String(x.id)===id);setLines(ls=>ls.map((l,n)=>n===i?{...l,product_id:id,batch_id:'',gst_rate:String(p?.gst_rate??0),selling_price:String(p?.default_selling_price??'')}:l))}
 const chooseBatch=(i:number,id:string)=>{const b=batches.find(x=>String(x.id)===id);setLines(ls=>ls.map((l,n)=>n===i?{...l,batch_id:id,selling_price:l.selling_price||String(b?.mrp??'')}:l))}
 const available=(batchId:string)=>stock.find(s=>String(s.batch_id)===batchId)?.quantity_available??0

 const submit=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);setError('');setSuccess('');try{if(!customerId)throw new Error('Select a customer');if(!invoiceNumber.trim())throw new Error('Enter an invoice number');if(lines.some(l=>!l.product_id||!l.batch_id||!l.quantity||!l.selling_price))throw new Error('Complete every invoice line');for(const l of lines){if(Number(l.quantity)>available(l.batch_id))throw new Error(`Quantity exceeds available stock for a selected batch`)}const paid=paymentMode==='CREDIT'?0:Number(amountPaid||0);const inv=await apiClient.createSale({invoice_number:invoiceNumber.trim(),invoice_date:invoiceDate,customer_id:Number(customerId),tax_mode:taxMode,payment_mode:paymentMode,amount_paid:paid,payment_reference:paymentReference||null,notes,items:lines.map(l=>({product_id:Number(l.product_id),batch_id:Number(l.batch_id),quantity:Number(l.quantity),selling_price:Number(l.selling_price),discount_percent:Number(l.discount_percent||0),gst_rate:Number(l.gst_rate||0)}))});setSuccess(`Invoice ${inv.invoice_number} posted. Stock deducted automatically. Balance ₹${inv.balance_due}.`);setInvoiceNumber('');setNotes('');setPaymentMode('CREDIT');setAmountPaid('0');setPaymentReference('');setLines([blankLine()]);await load()}catch(e:any){setError(e?.response?.data?.detail||e.message||'Unable to post sale')}finally{setSaving(false)}}

 return <div className="min-h-screen bg-gray-50 p-6"><div className="mx-auto max-w-7xl">
  <div className="mb-6"><h1 className="text-2xl font-bold text-gray-900">Sales & Billing</h1><p className="text-sm text-gray-500">Create customer invoices from available batches and deduct inventory automatically.</p></div>
  {error&&<div className="mb-4 rounded border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}{success&&<div className="mb-4 rounded border border-green-200 bg-green-50 p-3 text-sm text-green-700">{success}</div>}
  <form onSubmit={submit} className="mb-8 rounded-lg bg-white p-5 shadow-sm"><div className="mb-4 grid gap-3 md:grid-cols-4"><select required value={customerId} onChange={e=>setCustomerId(e.target.value)} className="rounded border px-3 py-2"><option value="">Select customer</option>{customers.filter(c=>c.is_active!==false).map(c=><option key={c.id} value={c.id}>{c.customer_name} ({c.customer_code})</option>)}</select><input required placeholder="Invoice number" value={invoiceNumber} onChange={e=>setInvoiceNumber(e.target.value)} className="rounded border px-3 py-2"/><input required type="date" value={invoiceDate} max={new Date().toISOString().slice(0,10)} onChange={e=>setInvoiceDate(e.target.value)} className="rounded border px-3 py-2"/><select value={taxMode} onChange={e=>setTaxMode(e.target.value)} className="rounded border px-3 py-2"><option value="INTRA_STATE">CGST + SGST</option><option value="INTER_STATE">IGST</option></select></div>
   <div className="overflow-x-auto"><table className="min-w-[1050px] w-full text-sm"><thead><tr className="border-b text-left">{['Product','Batch / Expiry','Available','Qty','Selling Price','Disc %','GST %','Amount',''].map(h=><th className="p-2" key={h}>{h}</th>)}</tr></thead><tbody>{lines.map((l,i)=>{const amount=Number(l.quantity||0)*Number(l.selling_price||0)*(1-Number(l.discount_percent||0)/100)*(1+Number(l.gst_rate||0)/100);return <tr key={i} className="border-b"><td className="p-2"><select required value={l.product_id} onChange={e=>chooseProduct(i,e.target.value)} className="w-52 rounded border px-2 py-2"><option value="">Product</option>{products.map(p=><option key={p.id} value={p.id}>{p.product_name} ({p.product_code})</option>)}</select></td><td className="p-2"><select required disabled={!l.product_id} value={l.batch_id} onChange={e=>chooseBatch(i,e.target.value)} className="w-48 rounded border px-2 py-2"><option value="">Select batch</option>{productBatches(l.product_id).map(b=><option key={b.id} value={b.id}>{b.batch_number} · {b.expiry_date}</option>)}</select></td><td className="p-2 font-medium">{l.batch_id?available(l.batch_id):'-'}</td><td className="p-2"><input required type="number" min="1" max={l.batch_id?available(l.batch_id):undefined} value={l.quantity} onChange={e=>update(i,'quantity',e.target.value)} className="w-20 rounded border px-2 py-2"/></td><td className="p-2"><input required type="number" min="0" step="0.01" value={l.selling_price} onChange={e=>update(i,'selling_price',e.target.value)} className="w-28 rounded border px-2 py-2"/></td><td className="p-2"><input type="number" min="0" max="100" step="0.01" value={l.discount_percent} onChange={e=>update(i,'discount_percent',e.target.value)} className="w-20 rounded border px-2 py-2"/></td><td className="p-2"><input type="number" min="0" max="100" step="0.01" value={l.gst_rate} onChange={e=>update(i,'gst_rate',e.target.value)} className="w-20 rounded border px-2 py-2"/></td><td className="p-2 font-medium">₹{money(amount)}</td><td className="p-2"><button type="button" disabled={lines.length===1} onClick={()=>setLines(ls=>ls.filter((_,n)=>n!==i))} className="text-red-600 disabled:text-gray-300">Remove</button></td></tr>})}</tbody></table></div>
   <div className="mt-4 flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><button type="button" onClick={()=>setLines(ls=>[...ls,blankLine()])} className="w-fit rounded border px-4 py-2">+ Add line</button><div className="grid gap-2 text-sm sm:grid-cols-2 lg:w-[520px]"><select value={paymentMode} onChange={e=>{setPaymentMode(e.target.value);if(e.target.value==='CREDIT')setAmountPaid('0')}} className="rounded border px-3 py-2"><option value="CREDIT">Credit</option><option value="CASH">Cash</option><option value="UPI">UPI</option><option value="CARD">Card</option><option value="BANK">Bank</option></select><input type="number" min="0" step="0.01" disabled={paymentMode==='CREDIT'} value={amountPaid} onChange={e=>setAmountPaid(e.target.value)} placeholder="Amount paid" className="rounded border px-3 py-2 disabled:bg-gray-100"/><input value={paymentReference} onChange={e=>setPaymentReference(e.target.value)} placeholder="Payment reference (optional)" className="rounded border px-3 py-2 sm:col-span-2"/></div><div className="min-w-56 text-right text-sm"><div>Subtotal: ₹{money(totals.subtotal)}</div><div>Discount: ₹{money(totals.discount)}</div><div>Taxable: ₹{money(totals.taxable)}</div><div>GST: ₹{money(totals.tax)}</div><div className="text-lg font-bold">Grand total: ₹{money(totals.total)}</div></div></div>
   <textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Notes (optional)" className="mt-4 w-full rounded border px-3 py-2" rows={2}/><div className="mt-4 text-right"><button disabled={saving} className="rounded bg-blue-600 px-5 py-2 text-white disabled:opacity-50">{saving?'Posting...':'Create Invoice & Deduct Stock'}</button></div>
  </form>
  <div className="rounded-lg bg-white shadow-sm"><div className="border-b p-4 font-semibold">Sales history</div>{loading?<div className="p-6 text-center text-gray-500">Loading...</div>:invoices.length===0?<div className="p-6 text-center text-gray-500">No sales invoices yet.</div>:<div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="border-b bg-gray-50"><tr><th className="p-3 text-left">Date</th><th className="p-3 text-left">Invoice #</th><th className="p-3 text-left">Customer</th><th className="p-3 text-right">Total</th><th className="p-3 text-right">Paid</th><th className="p-3 text-right">Balance</th><th className="p-3 text-left">Status</th></tr></thead><tbody>{invoices.map(i=><tr key={i.id} className="border-b"><td className="p-3">{i.invoice_date}</td><td className="p-3 font-medium">{i.invoice_number}</td><td className="p-3">{i.customer_name}</td><td className="p-3 text-right">₹{i.grand_total}</td><td className="p-3 text-right">₹{i.amount_paid}</td><td className="p-3 text-right">₹{i.balance_due}</td><td className="p-3">{i.payment_status}</td></tr>)}</tbody></table></div>}</div>
 </div></div>
}
